# GitHub Action for generating a contribution graph with a snake eating your contributions.

### 🐍 Snake Animation

# ![Snake animation](https://github.com/kallianaa/kallianaa/blob/output/github-contribution-grid-snake.svg)

name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas

  workflow_dispatch:  # Permite rodar manualmente pelo Actions
  
  push:
    branches:
      - main  # Roda sempre que houver um push na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: kallianaa
          output_format: transparent  # Versão padrão (transparente)
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show build status
        run: git status

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update snake animations"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
